name:                correctMe
version:             0.1.0.0
github:              "githubuser/correctMe"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/correctMe#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- hasql
- hasql-pool
- hasql-th
- mtl
- profunctors
- servant
- servant-server
- text
- vector
- wai
- warp


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- OverloadedStrings
- QuasiQuotes
- DataKinds
- DeriveGeneric
- DeriveFunctor
- TemplateHaskell
- TypeOperators
- FlexibleContexts
- GeneralizedNewtypeDeriving

library:
  source-dirs: src

executables:
  correctMe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - correctMe

tests:
  correctMe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - correctMe
